apiVersion: logging.grafana.com/v1beta1
kind: Promtail
metadata:
  name: promtail
  namespace: loki
spec:
  clients:
    # Die URL muss auf deinen Loki-Service im "loki" Namespace zeigen
    - url: http://loki.loki.svc.cluster.local:3100/loki/api/v1/push
  podSelector:
    matchExpressions:
      # Diese Labels filtern die Pods, von denen Logs gesammelt werden sollen.
      # Hier werden alle Pods mit den Labels von Istio erfasst.
      - key: app.kubernetes.io/name
        operator: In
        values:
          - istiod
          - istio-ingressgateway
      - key: app.kubernetes.io/part-of
        operator: In
        values:
          - istio
  serviceAccountName: promtail
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: promtail
  namespace: loki
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: promtail
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - services
      - endpoints
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes/metrics
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: promtail
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: promtail
subjects:
  - kind: ServiceAccount
    name: promtail
    namespace: loki
