spec:
  type: NodePort
  ports:
  - name: status-port
    port: 15021
    targetPort: 15021
    nodePort: 30002
    protocol: TCP
  - name: http2
    port: 80
    targetPort: 80
    nodePort: 30000
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    nodePort: 30001
    protocol: TCP