kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kindcluster
networking:
  ipFamily: ipv4
  apiServerAddress: "192.168.178.170"
  apiServerPort: 6443
  podSubnet: "192.168.0.0/16"
  disableDefaultCNI: true
  kubeProxyMode: "iptables"
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 9080
    protocol: TCP
  - containerPort: 443
    hostPort: 9443
    protocol: TCP
  - containerPort: 30000
    hostPort: 80
    protocol: TCP
  - containerPort: 30001
    hostPort: 443
    protocol: TCP
  - containerPort: 30002
    hostPort: 15021
    protocol: TCP    
- role: worker
  extraMounts:
  - hostPath: /data
    containerPath: /data
    readOnly: false
    selinuxRelabel: false
    propagation: HostToContainer

