---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 172.18.100.10-172.18.100.100
# docker network inspect -f '{{.IPAM.Config}}' kind
