---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 172.18.250.10-172.18.250.250
# docker network inspect -f '{{.IPAM.Config}}' kind
