apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: dbclient
type: Opaque
stringData:
  MYSQL_HOST: gmkchost.lan
  MYSQL_PORT: "3306"
  MYSQL_USER: restdata
  MYSQL_PASSWORD: restdata
  MYSQL_DATABASE: restdata
