apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: mirrorservice-kaniko
  namespace: argo-workflows
spec:
  entrypoint: main
  serviceAccountName: workflow-sa
  arguments:
    parameters:
      - name: image-tag
        value: latest
      - name: git-ref
        value: refs/heads/main
      - name: dockerfile
        value: Dockerfile

  templates:
    - name: main
      steps:
        - - name: build
            template: kaniko-build
        - - name: update-chart
            template: git-update

    - name: kaniko-build
      container:
        image: gcr.io/kaniko-project/executor:latest
        command: [/kaniko/executor]
        args:
          - "--dockerfile={{workflow.parameters.dockerfile}}"
          - "--context=git://github.com/wlanboy/MirrorService.git#{{workflow.parameters.git-ref}}"
          - "--destination=docker.io/wlanboy/mirrorservice:{{workflow.parameters.image-tag}}"
          - "--destination=docker.io/wlanboy/mirrorservice:latest"
        env:
          - name: DOCKER_CONFIG
            value: /kaniko/.docker
        volumeMounts:
          - name: docker-config
            mountPath: /kaniko/.docker
      volumes:
        - name: docker-config
          secret:
            secretName: regcred
            items:
              - key: .dockerconfigjson
                path: config.json

    - name: git-update
      script:
        image: docker.io/alpine/git:latest
        command: [sh]
        source: |
          TOKEN=$(cat /var/run/secrets/github/token)
          TAG="{{workflow.parameters.image-tag}}"

          git clone "https://wlanboy:${TOKEN}@github.com/wlanboy/MirrorService.git" /tmp/repo
          cd /tmp/repo/mirror-chart

          sed -i "s|^  tag:.*|  tag: ${TAG}|" values.yaml

          git config user.email "argo-workflows@gmk.lan"
          git config user.name "Argo Workflows"
          git add values.yaml
          git diff --cached --quiet && echo "Nothing to commit." && exit 0
          git commit -m "chore: update image.tag to ${TAG}"
          git push "https://wlanboy:${TOKEN}@github.com/wlanboy/MirrorService.git"
        volumeMounts:
          - name: github-token
            mountPath: /var/run/secrets/github
      volumes:
        - name: github-token
          secret:
            secretName: github-token
            items:
              - key: token
                path: token
