apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: mirrorservice-kaniko
  namespace: argocd
spec:
  entrypoint: build
  serviceAccountName: workflow-sa
  arguments:
    parameters:
      - name: image-tag
        value: latest

  templates:
    - name: build
      container:
        image: gcr.io/kaniko-project/executor:latest
        command: [/kaniko/executor]
        args:
          - "--dockerfile=Dockerfile"
          - "--context=git://github.com/wlanboy/MirrorService.git#refs/tags/{{workflow.parameters.image-tag}}"
          - "--destination=docker.io/wlanboy/mirrorservice:{{workflow.parameters.image-tag}}"
          - "--destination=docker.io/wlanboy/mirrorservice:latest"
        env:
          - name: DOCKER_CONFIG
            value: /kaniko/.docker

        volumeMounts:
          - name: docker-config
            mountPath: /kaniko/.docker

      volumes:
        - name: docker-config
          secret:
            secretName: regcred
            items:
              - key: .dockerconfigjson
                path: config.json
