apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: mirrorservice-buildkit
  namespace: argo-workflows
spec:
  entrypoint: main
  serviceAccountName: workflow-sa
  arguments:
    parameters:
      - name: image-tag
        value: latest
      - name: git-ref
        value: refs/heads/main
      - name: dockerfile
        value: Dockerfile

  templates:
    - name: main
      steps:
        - - name: build
            template: buildkit-build
        - - name: update-chart
            template: git-update

    - name: buildkit-build
      script:
        image: moby/buildkit:rootless
        command: [sh]
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          seccompProfile:
            type: Unconfined
          appArmorProfile:
            type: Unconfined
          capabilities:
            add: ["SYS_ADMIN"]
        source: |
          TAG={{workflow.parameters.image-tag}}
          export XDG_RUNTIME_DIR=/tmp/xdg
          mkdir -p ${XDG_RUNTIME_DIR}
          rootlesskit buildkitd --oci-worker-no-process-sandbox &
          for i in $(seq 1 30); do
            buildctl --addr unix://${XDG_RUNTIME_DIR}/buildkit/buildkitd.sock debug workers 2>/dev/null && break
            sleep 1
          done
          buildctl --addr unix://${XDG_RUNTIME_DIR}/buildkit/buildkitd.sock build \
            --frontend=dockerfile.v0 \
            --opt context=https://github.com/wlanboy/MirrorService.git#{{workflow.parameters.git-ref}} \
            --opt filename={{workflow.parameters.dockerfile}} \
            --output "type=image,name=docker.io/wlanboy/mirrorservice:${TAG},name=docker.io/wlanboy/mirrorservice:latest,push=true" \
            --export-cache type=registry,ref=local-registry.argo-workflows.svc.cluster.local:5000/cache/mirrorservice,mode=max,registry.insecure=true \
            --import-cache type=registry,ref=local-registry.argo-workflows.svc.cluster.local:5000/cache/mirrorservice,registry.insecure=true
        env:
          - name: DOCKER_CONFIG
            value: /home/user/.docker
        volumeMounts:
          - name: docker-config
            mountPath: /home/user/.docker
      volumes:
        - name: docker-config
          secret:
            secretName: regcred
            items:
              - key: .dockerconfigjson
                path: config.json

    - name: git-update
      script:
        image: docker.io/alpine/git:latest
        command: [sh]
        source: |
          TOKEN=$(cat /var/run/secrets/github/token)
          TAG="{{workflow.parameters.image-tag}}"

          git clone "https://wlanboy:${TOKEN}@github.com/wlanboy/MirrorService.git" /tmp/repo
          cd /tmp/repo/mirror-chart

          sed -i "s|^  tag:.*|  tag: ${TAG}|" values.yaml

          git config user.email "argo-workflows@gmk.lan"
          git config user.name "Argo Workflows"
          git add values.yaml
          git diff --cached --quiet && echo "Nothing to commit." && exit 0
          git commit -m "chore: update image.tag to ${TAG}"
          git push "https://wlanboy:${TOKEN}@github.com/wlanboy/MirrorService.git"
        volumeMounts:
          - name: github-token
            mountPath: /var/run/secrets/github
      volumes:
        - name: github-token
          secret:
            secretName: github-token
            items:
              - key: token
                path: token
