---
- name: Promtail Helm-Chart Overrides aus Template generieren
  ansible.builtin.template:
    src: promtail-overrides.yaml.j2
    dest: /tmp/promtail-overrides.yaml
    mode: '0644'

- name: Promtail mit Helm installieren/aktualisieren
  kubernetes.helm:
    name: promtail
    chart_ref: grafana/promtail
    namespace: istio-system
    create_namespace: true
    state: present
    wait: true
    values_files:
      - /tmp/promtail.yaml
