apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildkitd
  namespace: tekton
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buildkitd
  template:
    metadata:
      labels:
        app: buildkitd
    spec:
      containers:
        - name: buildkitd
          image: moby/buildkit:rootless
          command: ["sh", "-c"]
          args:
            - |
              export XDG_RUNTIME_DIR=/tmp/xdg
              mkdir -p ${XDG_RUNTIME_DIR}
              exec rootlesskit --net=host \
                buildkitd \
                --addr tcp://0.0.0.0:1234 \
                --oci-worker-no-process-sandbox
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            seccompProfile:
              type: Unconfined
            appArmorProfile:
              type: Unconfined
            capabilities:
              add: ["SYS_ADMIN"]
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "2"
              memory: "1Gi"
          ports:
            - containerPort: 1234
              name: tcp
          readinessProbe:
            exec:
              command:
                - buildctl
                - --addr
                - tcp://127.0.0.1:1234
                - debug
                - workers
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            exec:
              command:
                - buildctl
                - --addr
                - tcp://127.0.0.1:1234
                - debug
                - workers
            initialDelaySeconds: 10
            periodSeconds: 30
            failureThreshold: 3
            timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: buildkitd
  namespace: tekton
spec:
  selector:
    app: buildkitd
  ports:
    - port: 1234
      targetPort: 1234
      name: tcp
