apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: randomfail-buildkit-
  namespace: tekton
spec:
  pipelineRef:
    name: buildkit-pipeline
  serviceAccountName: workflow-sa
  params:
    - name: github-repo
      value: "wlanboy/randomfail"
    - name: image-name
      value: "docker.io/wlanboy/randomfail"
    - name: cache-name
      value: "randomfail"
    - name: chart-dir
      value: "randomfail-chart"
    - name: git-ref
      value: "refs/heads/main"
    - name: dockerfile
      value: "Dockerfile"
    - name: image-tag
      value: "latest"
    - name: push
      value: "true"
