apiVersion: v1
kind: Secret
metadata:
  name: cluster-local
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
stringData:
  name: local
  server: https://kubernetes.default.svc
