apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: workflow-complete
  namespace: argocd
spec:
  resource:
    build-succeeded:
      group: argoproj.io
      version: v1alpha1
      resource: workflows
      namespace: argocd
      eventTypes:
        - ADD
        - UPDATE
      filter:
        fields:
          - key: status.phase
            value: Succeeded
        labels:
          - key: argocd-app
            operation: "!="
            value: ""
