kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kindcluster
networking:
  ipFamily: ipv4
  apiServerAddress: "192.168.178.120"
  apiServerPort: 6443
  podSubnet: "192.168.0.0/16"
  disableDefaultCNI: true
  kubeProxyMode: "iptables"
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
- role: worker
